language: node_js
node_js:
  - "10.15"
  - "11.15"
  - "12.3"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run coverage
  - npm run report-coverage
after_success:
  coveralls < ./coverage/lcov.info
  